name: Push File
on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'LICENSE'
        destination_repo: 'github.com/arlou/test'
        destination_folder: 'out'
        user_email: 'arlou.yang@gmail.com'
        user_name: 'arlou'
        commit_message: 'A custom message for the commit'
