name: A workflow for my trial
on: pull_request

jobs:
  build:
    name: show secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "Hello $FIRST_NAME $middle_name $Last_Name, today is Monday!"
      - run: echo "Hello $API_TOKEN_GITHUB"
      - run: exit 0
    env:
          FIRST_NAME: Mona
          middle_name: The
          Last_Name: Octocat
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
