name: A workflow for my trial
on: push

jobs:
  build:
    name: show secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "Hello $FIRST_NAME $middle_name $Last_Name, today is Monday!"
    env:
          FIRST_NAME: Mona
          middle_name: The
          Last_Name: Octocat
